# - name: Create Pi-Hole Directories
#   file:
#     path: "{{ item }}"
#     state: directory
#     # mode: 0755
#   with_items:
#     - "{{ pihole_config_directory }}"

- name: Create Pi-Hole Directories
  file:
    path: "{{ pihole_conf }}"
    state: directory

- name: Create Pi-Hole Directories
  file:
    path: "{{ pihole_dnsmasq }}"
    state: directory

- name: Create Pi-Hole Directories
  file:
    path: "{{ pihole_log }}"
    state: directory

- name: Create Pi-Hole Directories
  file:
    path: "{{ pihole_log }}pihole.log"
    state: touch

- name: JWilder reverse proxy
  docker_container:
    name: revproxy
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    env:
      DEFAULT_HOST: pihole.mousehouse.lan
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: yes

- name: Pi-Hole Docker Container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    dns_servers:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8053:80/tcp'
      - "443:443/tcp"
    volumes:
      - '{{ pihole_conf }}:/etc/pihole/'
      - '{{ pihole_dnsmasq }}:/etc/dnsmasq.d/'
      - '{{ pihole_log }}/pihole.log:/var/log/pihole.log'
      #       - './etc-pihole/:/etc/pihole/'
      # - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # - './var-log/pihole.log:/var/log/pihole.log'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    capabilities:
      - NET_ADMIN
    env:
      ServerIP: 192.168.1.99
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.mousehouse.lan
      VIRTUAL_PORT: "80"
      WEBPASSWORD: "qwerty123"
      TZ: "{{ ansible_nas_timezone }}"
    etc_hosts: >
      {
        "nw2master.bioware.com" : "0.0.0.0",
        "nwn2.master.gamespy.com" : "0.0.0.0",
        "mousehouse.lan" : "192.168.1.99",
        "pihole" : "192.168.1.99",
        "pihole.mousehouse.lan" : "192.168.1.99"
      }
      # Resolve to nothing domains (terminate connection)
      # - nw2master.bioware.com: 0.0.0.0
      # - nwn2.master.gamespy.com: 0.0.0.0
      # LAN hostnames for other docker containers using jwilder
      # - mousehouse.lan: 192.168.1.99
      # - pihole: 192.168.1.99
      # - pihole.mousehouse.lan: 192.168.1.99
      # - 'ghost ghost.yourDomain.lan:192.168.41.55'
      # - 'wordpress wordpress.yourDomain.lan:192.168.41.55'
    restart_policy: always

#   Another container you might want to have running through the proxy
#   Note it also have ENV Vars like pihole and a host under pihole's extra_hosts
#  ghost:
#    image: fractalf/ghost
#    ports:
#      - '2368:2368/tcp'
#    volumes:
#      - '/etc/ghost/:/ghost-override'
#    environment:
#      PROXY_LOCATION: ghost
#      VIRTUAL_HOST: ghost.yourDomain.lan
#      VIRTUAL_PORT: 2368
#    restart: always
